name: Generate Cheat Sheet

on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - '**.adoc'
      - 'theme/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@0b496e91ec7ae4428c3ed2eeb4c3a40df431f2cc
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          modules-
    - name: NPM Install
      run: npm install
      env:
        CI: true
    - name: AsciiDoctor-PDF
      run: npm run generate-pdf
    - name: Publish
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions"
        git add actions-cheat-sheet.*
        git commit -m 'AsciiDoctor-PDF build from Actions'
        git push --force origin HEAD:${GITHUB_REF#refs/heads/}
