name: Experiment

on:
  issues: 
    types: [labeled]
env:
  message: 'world'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, ${message}!
